### ISSUE TITLE
Migrate from vue2 to vue3 syntax

### ISSUE THREAD

**Issue by DuvanArwenLazar** [Lana-Software/una-red#4]
Migrar from vue 2 syntax to vue 3 cuose vue 2 is fuckin ugly

_Originally posted by @JohnGolgota in https://github.com/Lana-Software/una-red/pull/3#discussion_r1460663195_

**Comment by JohnGolgota** [comment]
pnpm run Lint @Kolozuz

**Comment by Kolozuz** [comment]
> pnpm run Lint @Kolozuz 

Contexto

**Comment by JohnGolgota** [comment]
> > pnpm run Lint @Kolozuz
> 
> Contexto

fix the title

**Comment by Kolozuz** [comment]
> > > pnpm run Lint @Kolozuz
> > 
> > Contexto
> 
> fix the title

Ah jajajajajahaahahhahah got it
