### ISSUE TITLE
🐞 [Bug]: Navbar redirect not working

### ISSUE THREAD

**Issue by JohnGolgota** [Lana-Software/una-red#5]
May can fix with router.push as an action on elements of the navbar.
I'm going to accept that I'm stupid and let him do the navigation bar like before. Go on

**Comment by DuvanArwenLazar** [comment]
Congratulations

**Comment by JohnGolgota** [comment]
This men si es gay, no mencione esto en el pr, kbron lo cerro el que no era.

**Comment by DuvanArwenLazar** [comment]
Joa
